version: "3.3"
services:
  oriondb:
    image: mongo
    command: --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo 
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/orion.db.root.password 
      - MONGO_INITDB_DATABASE=admin
      - ORIONDB_PASSWORD_FILE=/run/secrets/orion.db.password
    volumes:
      - orion-db:/data/db
      - ./oriondb:/docker-entrypoint-initdb.d
    deploy:
      replicas: 1
    networks:
      - orion
    secrets:
      - orion.db.root.password
      - orion.db.password
  orion:
    build: ./orion
    image: my-orion
    environment:
      - DB_HOST=oriondb 
      - DB=orion 
      - DB_USER=orion 
      - DB_PASSWORD_FILE=/run/secrets/orion.db.password
    deploy:
      replicas: 1
    ports:
      - "1026:1026"
    networks:
      - orion
    secrets:
      - orion.db.password

networks:
  orion:
secrets:
  orion.db.root.password:
    file: ./secrets/orion.db.root.password
  orion.db.password:
    file: ./secrets/orion.db.password
volumes:
  orion-db: