version: "3.5"
services:
  keyrock:
    build: ./keyrock
    image: my-idm:7.8.0
    depends_on:
      - mysql-db
    ports:
      - "3000:3000"
    environment:
      - IDM_CORS_ENABLED=true 
      - IDM_DB_HOST=mysql-db
      - IDM_HOST=http://192.168.1.32:3000
      - IDM_PORT=3000
      - IDM_DB_USER=root
      - IDM_ADMIN_USER=admin
      - IDM_ADMIN_EMAIL=admin@example.com
      - IDM_EMAIL_ADDRESS=noreply@example.com
      - IDM_TITLE=My Identity Manager
      - IDM_THEME=mytheme
      - IDM_PDP_LEVEL=advanced
      - IDM_AUTHZFORCE_ENABLED=true
      - IDM_AUTHZFORCE_HOST=authzforce
      - IDM_SESSION_SECRET_FILE=/run/secrets/idm.session.secret
      - IDM_ENCRYPTION_KEY_FILE=/run/secrets/idm.encryption.key 
      - IDM_DB_PASS_FILE=/run/secrets/idm.db.root.pass
      - IDM_ADMIN_PASS_FILE=/run/secrets/idm.admin.pass
    secrets:
      - idm.session.secret
      - idm.encryption.key
      - idm.db.root.pass
      - idm.admin.pass
    networks:
      default:
        ipv4_address: 172.21.1.5
  mysql-db:
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/idm.db.root.pass
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.21.1.6
    secrets:
      - idm.db.user.pass
      - idm.db.root.pass
  authzforce:
    restart: always
    image: fiware/authzforce-ce-server:release-8.1.0
    ports:
      - 8081:8080
    networks:
      default:
        ipv4_address: 172.21.1.7
networks:
  default:
    ipam:
      config:
        - subnet: 172.21.1.0/24
volumes:
  mysql-db:
secrets:
  idm.session.secret:
    file: ./secrets/idm.session.secret
  idm.encryption.key:
    file: ./secrets/idm.encryption.key
  idm.db.user.pass:
    file: ./secrets/idm.db.user.pass
  idm.db.root.pass:
    file: ./secrets/idm.db.root.pass
  idm.admin.pass:
    file: ./secrets/idm.admin.pass
