version: "3.5"
services:
  pep-proxy:
    image: marcdespland/fiware-pep-proxy
    container_name: pep-proxy
    hostname: pepproxy
    ports:
      - "8090:8080"
    environment:
      - PEP_PROXY_AUTH_ENABLED=true
      - PEP_PROXY_PUBLIC_PATHS=/public
      - PEP_PROXY_AZF_PORT=8081
      - PEP_PROXY_AZF_HOST=192.168.1.32
      - PEP_PROXY_AZF_PROTOCOL=http
      - PEP_PROXY_PDP=authzforce
      - PEP_PROXY_APP_SSL_ENABLED=false
      - PEP_PROXY_APP_PORT=8081
      - PEP_PROXY_APP_HOST=nginx
      - PEP_PROXY_APP_ID=24c00968-b065-4f5e-a1be-b72602257be3
      - PEP_PROXY_IDM_SSL_ENABLED=false
      - PEP_PROXY_IDM_PORT=3000
      - PEP_PROXY_IDM_HOST=192.168.1.32
      - PEP_PROXY_PORT=8080
      - PEP_PASSWORD_FILE=/run/secrets/pep.password
      - PEP_PROXY_USERNAME_FILE=/run/secrets/pep.proxy.username
    secrets:
      - pep.token.secret
      - pep.password
      - pep.proxy.username
    networks:
      default:
        ipv4_address: 172.18.1.2
  nginx:
    build: ./nginx
    image: my-proxy
    container_name: nginx
    hostname: nginx
    environment:
      - NGINX_PORT=8081
      - NGINX_HOST=172.18.1.3
      - PEP_PROXY_IP=172.18.1.2
      - NGSI_AGENTS_IP=192.168.1.32
      - ORION_IP=192.168.1.32
    networks:
      default:
        ipv4_address: 172.18.1.3
secrets:
  pep.proxy.username:
    file: ./secrets/pep.proxy.username
  pep.password:
    file: ./secrets/pep.password
  pep.token.secret:
    file: ./secrets/pep.token.secret
networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24
